---
kind: pipeline
type: docker
name: test-and-publish

steps:
- name: pytest
  image: python:latest
  commands:
    - python -m pip install .
    - python -m pip install -r requirements-dev.txt
    - make test
- name: pypi_publish
  image: python:latest
  when:
    event: tag
    tag: 'v\d+.\d+.d+*'
  environment:
    PYPI_TOKEN:
      from_secret: PYPI_TOKEN
  commands:
    - python -m pip install --upgrade setuptools build twine
    - python -m build --sdist --outdir dist/ .
    - python -m twine upload dist/* --username __token__ --password $PYPI_TOKEN

#pipeline:
#  test:
#    image: python:latest
#    commands:
#      - python -m pip install .
#      - python -m pip install -r requirements-dev.txt
#      - make test

#  pypi_publish:
#    when:
#      event: tag
#      tag: '[0-9]+.[0-9]+.[0-9]+*'
#    secrets: [pypi_api_token]
#    image: python:latest
#    commands:
#      - python -m pip install --upgrade setuptools build twine
#      - python -m build --sdist --outdir dist/ .
#      - python -m twine upload dist/* --username __token__ --password $PYPI_API_TOKEN
#
##    image: plugins/pypi
##    settings:
##      username: tandav
##      password:
##        from_secret: pypi_api_token
#
#branches: master
