pipeline:
  test:
    image: python:latest
    commands:
      - python -m pip install -r requirements.txt
      - python -m pip install -r requirements-dev.txt
      - make test

  pypi_publish:
    when:
      event: tag
      tag: '[0-9]+.[0-9]+.[0-9]+*'
    secrets: [pypi_api_token]
    image: python:latest
    commands:
      - python -m pip install --upgrade setuptools build twine
      - python -m build --sdist --outdir dist/ .
      - python -m twine upload --password ${PYPI_API_TOKEN} dist/*

#    image: plugins/pypi
#    settings:
#      username: tandav
#      password:
#        from_secret: pypi_api_token

branches: master
