[tool.isort]
line_length = 120
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
include_trailing_comma = true
force_single_line = true
indent = 4

[tool.autopep8]
max_line_length = 250
ignore = "E501,W503,E701,E704,E721,E741,I100,I201,W504"
recursive = true
aggressive = 3
